[package]
name = "win-unique"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wmi = "0.12.2"
windows = "0.48.0"
serde = "1.0.160"
